services:
  instawatch:
    build: .
    ports:
      - "18080:8080"
    volumes:
      - instawatch-data:/data
    restart: unless-stopped
    environment:
      - INSTAGRAM_SESSION_ID=${INSTAGRAM_SESSION_ID}

volumes:
  instawatch-data:
