services:
  instawatch:
    build: .
    image: ghcr.io/jadolg/instawatch:latest
    ports:
      - "8080:8080"
    volumes:
      - instawatch-data:/data
    restart: unless-stopped
    environment:
      - INSTAGRAM_SESSION_ID=${INSTAGRAM_SESSION_ID}
      - FACEBOOK_SESSION_ID=${FACEBOOK_SESSION_ID}

volumes:
  instawatch-data:
